### ISSUE TITLE
Weg mit Unterdrückung 

### ISSUE THREAD

**Issue by nicolasmeier** [patrickgue/Tschava#2]
Dä haupt branch sött "main" oder "haupt" heisse und nid "master"

https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by patrickgue** [comment]
mit de veränderig vo de Sprach hesch halt t Welt leider nanig verändered 

Kompromissvorschlag: De `master`-branch wird i `meister` umbenennt, um de tschava-Witz fortzfüehre, dezue het das wort uf schwizertütsch die konotation wie im englische nöd

**Comment by nicolasmeier** [comment]
isch e akzeptabli lösig

**Comment by patrickgue** [comment]
`master` heisst jetzt `meister`
